#!/usr/bin/env python3
from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CASES = ROOT / "cases"
EXPECTED = ROOT / "expected"
BUILD = ROOT / "build"
PASS_COUNT = 0


def run(cmd, env=None, input_text=None):
    return subprocess.run(
        cmd,
        input=input_text,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
        env=env,
    )


def req(condition, name, detail=""):
    global PASS_COUNT
    if condition:
        PASS_COUNT += 1
        print(f"  PASS {name}")
        return
    print(f"  FAIL {name}")
    if detail:
        print(detail.rstrip())
    raise SystemExit(1)


def reg(text, number):
    match = re.search(rf"\br{number}\s*=\s*(0x[0-9a-fA-F]+|\d+)\b", text)
    return int(match.group(1), 0) if match else None


def execute(binary):
    script = "\n".join(
        [
            "reset",
            f"load {binary} 0x00001000",
            "set pc 0x00001000",
            "run",
            "regs",
            "status",
            "quit",
            "",
        ]
    )
    result = run(["t32-run"], input_text=script)
    return result, result.stdout + result.stderr


def compile_and_execute(cc, case_name, expected_r0, label):
    binary = BUILD / f"{case_name}.bin"
    result = run([str(cc), str(CASES / f"{case_name}.c"), "-o", str(binary)])
    req(result.returncode == 0 and binary.exists(), f"{label} program links", result.stderr)
    execution, output = execute(binary)
    req(execution.returncode == 0, f"{label} program executes", output)
    req(reg(output, 0) == expected_r0, f"{label} returns expected value", output)
    req(reg(output, 15) == 0xF000, f"{label} restores stack", output)
    req(re.search(r"state\s*=\s*halted", output, re.I) is not None, f"{label} halts", output)


def compare_assembly(cc, case_name, label):
    assembly = BUILD / f"{case_name}.s"
    result = run([str(cc), "-S", str(CASES / f"{case_name}.c"), "-o", str(assembly)])
    req(result.returncode == 0, f"{label} -S compile succeeds", result.stderr)
    req(result.stdout == "", f"{label} remains quiet by default", result.stdout)
    expected = EXPECTED / f"{case_name}.s"
    actual_text = assembly.read_text()
    expected_text = expected.read_text()
    actual_normalized = re.sub(r"^; generated by t32-cc .*?$",
                               "; generated by t32-cc <version>",
                               actual_text, count=1, flags=re.M)
    actual_normalized = re.sub(r"^; Stage [0-9]+ ABI",
                               "; Stage <stage> ABI",
                               actual_normalized, count=1, flags=re.M)
    expected_normalized = re.sub(r"^; generated by t32-cc .*?$",
                                 "; generated by t32-cc <version>",
                                 expected_text, count=1, flags=re.M)
    expected_normalized = re.sub(r"^; Stage [0-9]+ ABI",
                                 "; Stage <stage> ABI",
                                 expected_normalized, count=1, flags=re.M)
    req(actual_normalized == expected_normalized,
        f"{label} assembly matches", actual_text)
    return actual_text


def compile_assembly(cc, case_name, label):
    assembly = BUILD / f"{case_name}.s"
    result = run([str(cc), "-S", str(CASES / f"{case_name}.c"), "-o", str(assembly)])
    req(result.returncode == 0, f"{label} -S compile succeeds", result.stderr)
    req(result.stdout == "", f"{label} remains quiet by default", result.stdout)
    return assembly.read_text()


def main():
    cc = Path(sys.argv[1] if len(sys.argv) > 1 else "./t32-cc").resolve()
    req(cc.is_file(), "compiler exists", str(cc))

    shutil.rmtree(BUILD, ignore_errors=True)
    BUILD.mkdir(parents=True)

    print("Running t32-cc 0.24.1 struct-pointer/arrow regression tests...")

    version = run([str(cc), "--version"])
    req(version.returncode == 0, "--version exits successfully", version.stderr)
    req("t32-cc 0.24.1" in version.stdout, "--version reports 0.24.1", version.stdout)

    # Preserve earlier compiler milestones exactly.
    compare_assembly(cc, "return_42", "constant return")
    local_text = compare_assembly(cc, "local_x", "local variable")
    req("subi r15, r15, 4" in local_text, "local allocates four-byte stack slot")
    req("stw  r1, [r15]" in local_text, "initializer stored to local slot")
    req("ldw  r0, [r15]" in local_text, "local loaded into return register")
    req("addi r15, r15, 4" in local_text, "local stack slot released")

    assignment_text = compare_assembly(cc, "assignment", "literal assignment")
    req(assignment_text.count("stw  r1, [r15]") == 2, "literal assignment emits second store")

    compile_and_execute(cc, "local_x", 5, "local")
    compile_and_execute(cc, "local_negative", 0xFFFFFFF9, "negative local")
    compile_and_execute(cc, "assignment", 7, "literal assignment")
    compile_and_execute(cc, "assignment_repeated", 3, "repeated literal assignment")
    compile_and_execute(cc, "assignment_negative", 0xFFFFFFF7, "negative assignment")

    # First binary expression: one '+' and two simple operands.
    constant_add = compare_assembly(cc, "return_add_constants", "constant plus constant")
    req("movi r0, 0x00000005" in constant_add, "constant addition loads left operand")
    req("movi r1, 0x00000003" in constant_add, "constant addition loads right operand")
    req("add  r0, r0, r1" in constant_add, "constant addition emits ADD")

    local_add = compare_assembly(cc, "local_add_constant", "local plus constant")
    req("ldw  r0, [r15]" in local_add, "local addition loads local operand")
    req("add  r0, r0, r1" in local_add, "local addition emits ADD")

    constant_local = compare_assembly(cc, "constant_add_local", "constant plus local")
    req("movi r0, 0x00000003" in constant_local, "constant-left addition loads literal")
    req("ldw  r1, [r15]" in constant_local, "constant-left addition loads local")

    local_local = compare_assembly(cc, "local_add_local", "local plus local")
    req(local_local.count("ldw  r") == 2, "local plus local loads both operands")

    assignment_add = compare_assembly(cc, "assignment_add", "addition assignment")
    req("ldw  r1, [r15]" in assignment_add, "addition assignment loads current value")
    req("movi r2, 0x00000001" in assignment_add, "addition assignment loads increment")
    req("add  r1, r1, r2" in assignment_add, "addition assignment emits ADD")
    req(assignment_add.count("stw  r1, [r15]") == 2, "addition assignment stores updated value")

    # Second binary expression operator: subtraction with the same simple operands.
    constant_sub = compare_assembly(cc, "return_sub_constants", "constant minus constant")
    req("movi r0, 0x0000000A" in constant_sub, "constant subtraction loads left operand")
    req("movi r1, 0x00000003" in constant_sub, "constant subtraction loads right operand")
    req("sub  r0, r0, r1" in constant_sub, "constant subtraction emits SUB")

    local_sub = compare_assembly(cc, "local_sub_constant", "local minus constant")
    req("ldw  r0, [r15]" in local_sub, "local subtraction loads local operand")
    req("sub  r0, r0, r1" in local_sub, "local subtraction emits SUB")

    constant_sub_local = compare_assembly(cc, "constant_sub_local", "constant minus local")
    req("movi r0, 0x0000000A" in constant_sub_local, "constant-left subtraction loads literal")
    req("ldw  r1, [r15]" in constant_sub_local, "constant-left subtraction loads local")

    local_sub_local = compare_assembly(cc, "local_sub_local", "local minus local")
    req(local_sub_local.count("ldw  r") == 2, "local minus local loads both operands")

    assignment_sub = compare_assembly(cc, "assignment_sub", "subtraction assignment")
    req("ldw  r1, [r15]" in assignment_sub, "subtraction assignment loads current value")
    req("movi r2, 0x00000001" in assignment_sub, "subtraction assignment loads decrement")
    req("sub  r1, r1, r2" in assignment_sub, "subtraction assignment emits SUB")
    req(assignment_sub.count("stw  r1, [r15]") == 2, "subtraction assignment stores updated value")

    # Third binary expression operator: multiplication with the same simple operands.
    constant_mul = compare_assembly(cc, "return_mul_constants", "constant times constant")
    req("movi r0, 0x00000006" in constant_mul, "constant multiplication loads left operand")
    req("movi r1, 0x00000007" in constant_mul, "constant multiplication loads right operand")
    req("mul  r0, r0, r1" in constant_mul, "constant multiplication emits MUL")

    local_mul = compare_assembly(cc, "local_mul_constant", "local times constant")
    req("ldw  r0, [r15]" in local_mul, "local multiplication loads local operand")
    req("mul  r0, r0, r1" in local_mul, "local multiplication emits MUL")

    constant_mul_local = compare_assembly(cc, "constant_mul_local", "constant times local")
    req("movi r0, 0x00000007" in constant_mul_local, "constant-left multiplication loads literal")
    req("ldw  r1, [r15]" in constant_mul_local, "constant-left multiplication loads local")

    local_mul_local = compare_assembly(cc, "local_mul_local", "local times local")
    req(local_mul_local.count("ldw  r") == 2, "local times local loads both operands")

    assignment_mul = compare_assembly(cc, "assignment_mul", "multiplication assignment")
    req("ldw  r1, [r15]" in assignment_mul, "multiplication assignment loads current value")
    req("movi r2, 0x00000003" in assignment_mul, "multiplication assignment loads factor")
    req("mul  r1, r1, r2" in assignment_mul, "multiplication assignment emits MUL")
    req(assignment_mul.count("stw  r1, [r15]") == 2, "multiplication assignment stores updated value")

    # Fourth binary expression operator: signed division.
    constant_div = compare_assembly(cc, "expression_divide", "constant divided by constant")
    req("movi r0, 0x00000008" in constant_div, "constant division loads left operand")
    req("movi r1, 0x00000002" in constant_div, "constant division loads right operand")
    req("div  r0, r0, r1" in constant_div, "constant division emits DIV")

    local_div = compare_assembly(cc, "local_div_constant", "local divided by constant")
    req("ldw  r0, [r15]" in local_div, "local division loads local operand")
    req("div  r0, r0, r1" in local_div, "local division emits DIV")

    constant_div_local = compare_assembly(cc, "constant_div_local", "constant divided by local")
    req("movi r0, 0x0000002A" in constant_div_local, "constant-left division loads literal")
    req("ldw  r1, [r15]" in constant_div_local, "constant-left division loads local")

    local_div_local = compare_assembly(cc, "local_div_local", "local divided by local")
    req(local_div_local.count("ldw  r") == 2, "local divided by local loads both operands")

    assignment_div = compare_assembly(cc, "assignment_div", "division assignment")
    req("ldw  r1, [r15]" in assignment_div, "division assignment loads current value")
    req("movi r2, 0x00000006" in assignment_div, "division assignment loads divisor")
    req("div  r1, r1, r2" in assignment_div, "division assignment emits DIV")
    req(assignment_div.count("stw  r1, [r15]") == 2, "division assignment stores updated value")

    # T32 has no REM instruction. Remainder lowers to a - (a / b) * b.
    constant_rem = compare_assembly(cc, "return_rem_constants", "constant remainder constant")
    req("div  r13, r0, r1" in constant_rem, "remainder computes quotient in scratch register")
    req("mul  r13, r13, r1" in constant_rem, "remainder reconstructs divisible portion")
    req("sub  r0, r0, r13" in constant_rem, "remainder subtracts divisible portion")

    local_rem = compare_assembly(cc, "local_rem_constant", "local remainder constant")
    req("ldw  r0, [r15]" in local_rem, "local remainder loads local operand")
    req("div  r13, r0, r1" in local_rem, "local remainder emits synthesized division")

    assignment_rem = compare_assembly(cc, "assignment_rem", "remainder assignment")
    req("div  r13, r1, r2" in assignment_rem, "remainder assignment computes quotient")
    req("sub  r1, r1, r13" in assignment_rem, "remainder assignment restores remainder")
    req(assignment_rem.count("stw  r1, [r15]") == 2, "remainder assignment stores updated value")

    # Object mode still exports main for expression code.
    obj = BUILD / "local_add_constant.o"
    result = run([str(cc), "-c", str(CASES / "local_add_constant.c"), "-o", str(obj)])
    req(result.returncode == 0 and obj.exists(), "-c emits expression object", result.stderr)
    symbols = run(["t32-nm", str(obj)])
    req(symbols.returncode == 0 and re.search(r"\bmain\b", symbols.stdout), "expression object exports main", symbols.stdout + symbols.stderr)

    # Execute all supported operand combinations and assignment forms.
    compile_and_execute(cc, "return_add_constants", 8, "constant plus constant")
    compile_and_execute(cc, "local_add_constant", 8, "local plus constant")
    compile_and_execute(cc, "constant_add_local", 8, "constant plus local")
    compile_and_execute(cc, "local_add_local", 10, "local plus local")
    compile_and_execute(cc, "assignment_add", 6, "addition assignment")
    compile_and_execute(cc, "assignment_identifier_rhs", 5, "identifier assignment")
    compile_and_execute(cc, "assignment_expression_rhs", 9, "constant-expression assignment")
    compile_and_execute(cc, "assignment_repeated_increment", 3, "repeated increment")
    compile_and_execute(cc, "add_negative", 0xFFFFFFFB, "negative addition")

    compile_and_execute(cc, "return_sub_constants", 7, "constant minus constant")
    compile_and_execute(cc, "local_sub_constant", 7, "local minus constant")
    compile_and_execute(cc, "constant_sub_local", 7, "constant minus local")
    compile_and_execute(cc, "local_sub_local", 0, "local minus local")
    compile_and_execute(cc, "assignment_sub", 4, "subtraction assignment")
    compile_and_execute(cc, "assignment_constant_sub_local", 7, "constant-minus-local assignment")
    compile_and_execute(cc, "assignment_repeated_decrement", 1, "repeated decrement")
    compile_and_execute(cc, "sub_negative_result", 0xFFFFFFF8, "negative subtraction result")
    compile_and_execute(cc, "sub_negative_operand", 8, "subtract negative operand")

    compile_and_execute(cc, "return_mul_constants", 42, "constant times constant")
    compile_and_execute(cc, "local_mul_constant", 42, "local times constant")
    compile_and_execute(cc, "constant_mul_local", 42, "constant times local")
    compile_and_execute(cc, "local_mul_local", 36, "local times local")
    compile_and_execute(cc, "assignment_mul", 15, "multiplication assignment")
    compile_and_execute(cc, "assignment_constant_mul_local", 15, "constant-times-local assignment")
    compile_and_execute(cc, "assignment_repeated_double", 8, "repeated doubling")
    compile_and_execute(cc, "mul_negative_result", 0xFFFFFFF4, "negative multiplication result")
    compile_and_execute(cc, "mul_two_negatives", 12, "two-negative multiplication")


    compile_and_execute(cc, "expression_divide", 4, "constant divided by constant")
    compile_and_execute(cc, "local_div_constant", 7, "local divided by constant")
    compile_and_execute(cc, "constant_div_local", 7, "constant divided by local")
    compile_and_execute(cc, "local_div_local", 1, "local divided by local")
    compile_and_execute(cc, "assignment_div", 7, "division assignment")
    compile_and_execute(cc, "assignment_constant_div_local", 7, "constant-divided-by-local assignment")
    compile_and_execute(cc, "assignment_repeated_half", 16, "repeated halving")
    compile_and_execute(cc, "div_negative_dividend", 0xFFFFFFFB, "negative dividend division")
    compile_and_execute(cc, "div_negative_divisor", 0xFFFFFFFB, "negative divisor division")
    compile_and_execute(cc, "div_two_negatives", 5, "two-negative division")

    compile_and_execute(cc, "return_rem_constants", 2, "constant remainder constant")
    compile_and_execute(cc, "local_rem_constant", 2, "local remainder constant")
    compile_and_execute(cc, "constant_rem_local", 2, "constant remainder local")
    compile_and_execute(cc, "local_rem_local", 0, "local remainder local")
    compile_and_execute(cc, "assignment_rem", 2, "remainder assignment")
    compile_and_execute(cc, "rem_negative_dividend", 0xFFFFFFFE, "negative dividend remainder")
    compile_and_execute(cc, "rem_negative_divisor", 2, "negative divisor remainder")
    compile_and_execute(cc, "rem_two_negatives", 0xFFFFFFFE, "two-negative remainder")

    # Stage 9: structured expressions -- chaining, precedence, parentheses.
    compile_and_execute(cc, "expression_chained", 6, "left-associative chained addition")
    compile_and_execute(cc, "expression_chained_sub", 5, "left-associative chained subtraction")
    compile_and_execute(cc, "expression_chained_mul", 24, "left-associative chained multiplication")
    compile_and_execute(cc, "expression_chained_div", 4, "left-associative chained division")
    compile_and_execute(cc, "expression_chained_rem", 0, "left-associative chained remainder")
    compile_and_execute(cc, "expression_mixed_mul_add", 10, "multiplication before addition")
    compile_and_execute(cc, "expression_mixed_div_add", 5, "division before addition")
    compile_and_execute(cc, "expression_mixed_rem_mul", 4, "remainder/multiplication left associativity")
    compile_and_execute(cc, "expression_parenthesized", 3, "parenthesized expression")
    compile_and_execute(cc, "precedence_mul_before_add", 14, "multiplication precedence")
    compile_and_execute(cc, "precedence_div_before_sub", 16, "division precedence")
    compile_and_execute(cc, "parentheses_override", 20, "parentheses override precedence")
    compile_and_execute(cc, "parentheses_nested", 46, "nested parentheses")
    compile_and_execute(cc, "assignment_complex_expression", 11, "complex assignment expression")
    compile_and_execute(cc, "assignment_parenthesized_expression", 16, "parenthesized assignment expression")

    # Stage 10: comparison expressions produce canonical integer 0 or 1.
    eq_text = compare_assembly(cc, "comparison_eq_true", "equality comparison")
    req("xor  r0, r0, r1" in eq_text, "equality compares via XOR")
    req("shr  r0, r0, r10" in eq_text, "equality normalizes to Boolean")

    ne_text = compare_assembly(cc, "comparison_ne_true", "inequality comparison")
    req("xor  r0, r0, r1" in ne_text, "inequality compares via XOR")

    lt_text = compare_assembly(cc, "comparison_lt_true", "signed less-than comparison")
    req("sub  r10, r0, r1" in lt_text, "signed less-than computes difference")
    req("shr  r0, r10, r11" in lt_text, "signed less-than emits Boolean result")

    compare_assembly(cc, "comparison_le_equal", "signed less-than-or-equal comparison")
    compare_assembly(cc, "comparison_gt_true", "signed greater-than comparison")
    compare_assembly(cc, "comparison_ge_equal", "signed greater-than-or-equal comparison")

    compile_and_execute(cc, "comparison_eq_true", 1, "equality true")
    compile_and_execute(cc, "comparison_eq_false", 0, "equality false")
    compile_and_execute(cc, "comparison_ne_true", 1, "inequality true")
    compile_and_execute(cc, "comparison_ne_false", 0, "inequality false")
    compile_and_execute(cc, "comparison_lt_true", 1, "signed less-than true")
    compile_and_execute(cc, "comparison_lt_false", 0, "signed less-than false")
    compile_and_execute(cc, "comparison_le_equal", 1, "signed less-than-or-equal equality")
    compile_and_execute(cc, "comparison_le_false", 0, "signed less-than-or-equal false")
    compile_and_execute(cc, "comparison_gt_true", 1, "signed greater-than true")
    compile_and_execute(cc, "comparison_gt_false", 0, "signed greater-than false")
    compile_and_execute(cc, "comparison_ge_equal", 1, "signed greater-than-or-equal equality")
    compile_and_execute(cc, "comparison_ge_false", 0, "signed greater-than-or-equal false")
    compile_and_execute(cc, "comparison_both_arithmetic", 1, "comparison of arithmetic expressions")
    compile_and_execute(cc, "comparison_parenthesized", 1, "parenthesized arithmetic comparison")
    compile_and_execute(cc, "comparison_assignment", 1, "comparison assigned as integer value")
    compile_and_execute(cc, "comparison_as_value", 6, "comparison used inside arithmetic")
    compile_and_execute(cc, "comparison_rel_eq_precedence", 1, "relational before equality precedence")
    compile_and_execute(cc, "comparison_signed_min", 1, "INT32_MIN signed comparison")
    compile_and_execute(cc, "comparison_signed_max", 1, "INT32_MAX signed comparison")
    compile_and_execute(cc, "comparison_chain", 1, "left-associative relational chain")

    # Stage 11: first C control flow.
    if_true_text = compare_assembly(cc, "if_true", "if true")
    req("jz   r0, .Lendif_" in if_true_text, "if branches on zero condition")

    if_else_text = compare_assembly(cc, "if_else_true", "if/else")
    req("jz   r0, .Lelse_" in if_else_text, "if/else branches to else arm")
    req("jmp  .Lendif_" in if_else_text, "if/else skips else after true arm")
    req(".Lelse_" in if_else_text and ".Lendif_" in if_else_text,
        "if/else emits control-flow labels")

    compile_and_execute(cc, "if_true", 20, "true if")
    compile_and_execute(cc, "if_false", 15, "false if")
    compile_and_execute(cc, "if_else_true", 20, "true if/else")
    compile_and_execute(cc, "if_else_false", 30, "false if/else")
    compile_and_execute(cc, "if_truthy", 9, "nonzero condition")
    compile_and_execute(cc, "if_zero", 5, "zero condition")
    compile_and_execute(cc, "if_complex_condition", 11, "complex if condition")
    compile_and_execute(cc, "if_braced_multi", 12, "braced multi-statement if")
    compile_and_execute(cc, "if_else_braced", 30, "braced if/else")
    compile_and_execute(cc, "if_nested", 42, "nested if")
    compile_and_execute(cc, "if_else_if", 2, "else-if chain")
    compile_and_execute(cc, "if_empty_block", 5, "empty if block")

    # Stage 12: while loops.
    while_text = compare_assembly(cc, "while_basic", "basic while")
    req(".Lwhile_" in while_text, "while emits loop-head label")
    req("jz   r0, .Lendwhile_" in while_text, "while exits on zero condition")
    req("jmp  .Lwhile_" in while_text, "while branches back to loop head")
    req(".Lendwhile_" in while_text, "while emits exit label")

    compile_and_execute(cc, "while_basic", 5, "basic while")
    compile_and_execute(cc, "while_false", 7, "initially false while")
    compile_and_execute(cc, "while_truthy", 0, "truthy while countdown")
    compile_and_execute(cc, "while_braced_multi", 31, "multi-statement while")
    compile_and_execute(cc, "while_complex_condition", 11, "complex while condition")
    compile_and_execute(cc, "while_with_if", 5, "while containing if/else")
    compile_and_execute(cc, "while_nested", 16, "nested while")
    compile_and_execute(cc, "while_empty_false", 0, "empty false while")

    # Stage 13: multiple local variables and fixed stack slots.
    two_local_text = compare_assembly(cc, "multi_two_locals", "two locals")
    req("subi r15, r15, 8" in two_local_text,
        "two locals allocate eight-byte stack frame")
    req("local int x at [r15 + 0]" in two_local_text,
        "first local assigned slot zero")
    req("local int y at [r15 + 4]" in two_local_text,
        "second local assigned slot four")
    req("movi r10, 0x00000004" in two_local_text and
        "add  r10, r15, r10" in two_local_text,
        "second local addressed by fixed stack offset")
    req("addi r15, r15, 8" in two_local_text,
        "two-local stack frame released")

    compile_and_execute(cc, "two_locals", 1, "historical two-local declaration")
    compile_and_execute(cc, "multi_two_locals", 12, "two-local arithmetic")
    compile_and_execute(cc, "multi_assign_cross", 20, "cross-local assignments")
    compile_and_execute(cc, "multi_three_locals", 14, "three-local expression")
    compile_and_execute(cc, "multi_while_sum", 45, "two-local while accumulation")
    compile_and_execute(cc, "multi_if_mix", 25, "two-local if/else")
    compile_and_execute(cc, "multi_negative_values", 0xFFFFFFF6,
                        "negative multi-local arithmetic")

    # Stage 14: local initializers are full expressions.
    init_text = compare_assembly(cc, "init_from_local", "initializer from local")
    req("initialize local int y at [r15 + 4]" in init_text,
        "initializer identifies destination local")
    req("ldw  r1, [r15]" in init_text,
        "initializer loads previously declared local")
    req("add  r1, r1, r2" in init_text,
        "initializer evaluates arithmetic expression")
    req("stw  r1, [r10]" in init_text,
        "initializer stores computed value into later slot")

    compile_and_execute(cc, "multi_initializer_expression", 2,
                        "formerly-rejected initializer expression")
    compile_and_execute(cc, "init_from_local", 8, "initializer from prior local")
    compile_and_execute(cc, "init_chain", 42, "chained initializer dependencies")
    compile_and_execute(cc, "init_precedence", 14, "initializer precedence")
    compile_and_execute(cc, "init_parentheses", 20, "initializer parentheses")
    compile_and_execute(cc, "init_comparison", 1, "comparison initializer")
    compile_and_execute(cc, "init_negative_expression", 0xFFFFFFF3,
                        "negative initializer expression")
    compile_and_execute(cc, "init_used_by_loop", 8,
                        "expression-initialized loop bounds")

    # Stage 15: for loops, break, and continue.
    for_text = compare_assembly(cc, "for_basic", "basic for")
    req(".Lfor_" in for_text, "for emits condition label")
    req("jz   r0, .Lendfor_" in for_text, "for exits on zero condition")
    req(".Lfor_update_" in for_text, "for emits update label")
    req("jmp  .Lfor_" in for_text, "for loops back after update")

    break_text = compile_assembly(cc, "for_break", "for break")
    req("jmp  .Lendfor_" in break_text, "break targets innermost for exit")

    continue_text = compile_assembly(cc, "for_continue", "for continue")
    req("jmp  .Lfor_update_" in continue_text,
        "for continue targets update clause")

    while_continue_text = compile_assembly(cc, "while_continue", "while continue")
    req("jmp  .Lwhile_" in while_continue_text,
        "while continue targets condition label")

    compile_and_execute(cc, "for_basic", 5, "basic for")
    compile_and_execute(cc, "for_sum", 45, "for accumulation")
    compile_and_execute(cc, "for_break", 4, "for break")
    compile_and_execute(cc, "for_continue", 12, "for continue")
    compile_and_execute(cc, "while_break", 4, "while break")
    compile_and_execute(cc, "while_continue", 18, "while continue")
    compile_and_execute(cc, "nested_break", 6, "nested innermost break")
    compile_and_execute(cc, "nested_continue", 9, "nested innermost continue")

    # 0.14.1: ordinary C local declarations and implicit main return.
    uninit_text = compare_assembly(cc, "uninitialized_then_assign", "uninitialized local")
    req("uninitialized local int x" in uninit_text,
        "uninitialized local reserves stack slot")
    req(uninit_text.count("stw  r1, [r15]") == 1,
        "uninitialized local does not synthesize initialization store")

    compile_and_execute(cc, "uninitialized_then_assign", 5,
                        "uninitialized local then assignment")
    compile_and_execute(cc, "implicit_main_return", 0,
                        "implicit return zero from main")
    compile_and_execute(cc, "user_ordinary_main", 0,
                        "ordinary main compatibility sample")

    # Stage 16: multiple functions and ABI register parameters.
    function_text = compile_assembly(cc, "function_add", "two-parameter function")
    req("add:" in function_text and "main:" in function_text,
        "translation unit emits helper and main labels")
    req("parameter int a from r0" in function_text and
        "parameter int b from r1" in function_text,
        "callee receives first two ABI register parameters")
    req("call add" in function_text, "main emits CALL to helper")

    compile_and_execute(cc, "function_add", 30, "two-parameter function")
    compile_and_execute(cc, "function_local", 42, "function local stack frame")
    compile_and_execute(cc, "function_zero_arg", 42, "zero-argument function")
    compile_and_execute(cc, "function_four_args", 10, "four-register-argument function")
    compile_and_execute(cc, "function_forward", 42, "forward function reference")
    compile_and_execute(cc, "function_init_call", 15, "function call initializer")
    compile_and_execute(cc, "function_assign_call", 25, "function call assignment")

    # Stage 17: mature calls, early returns, and recursion groundwork.
    embedded_text = compile_assembly(cc, "function_call_in_expression",
                                     "call embedded in arithmetic")
    req("call add" in embedded_text and "add  r0" in embedded_text,
        "embedded call participates in arithmetic expression")

    rhs_text = compile_assembly(cc, "function_call_rhs", "call on RHS of arithmetic")
    req("call add" in rhs_text,
        "RHS call emitted with caller value preservation")

    early_text = compile_assembly(cc, "function_early_return", "early return")
    req("jmp  .Lreturn_choose" in early_text,
        "early return branches to shared function epilogue")

    compile_and_execute(cc, "function_call_in_expression", 6,
                        "call embedded in arithmetic")
    compile_and_execute(cc, "function_call_rhs", 17,
                        "call on right side of arithmetic")
    compile_and_execute(cc, "function_nested_calls", 42,
                        "function calling function")
    compile_and_execute(cc, "function_nested_arguments", 24,
                        "nested calls used as arguments")
    compile_and_execute(cc, "function_early_return", 7,
                        "early conditional return")
    compile_and_execute(cc, "function_multiple_returns", 2,
                        "multiple conditional returns")
    compile_and_execute(cc, "function_return_in_while", 4,
                        "return from loop")
    compile_and_execute(cc, "function_recursive_factorial", 120,
                        "recursive factorial groundwork")
    compile_and_execute(cc, "function_locals_parameters", 27,
                        "locals and parameters together")

    compile_and_execute(cc, "invalid_return_in_if", 1,
                        "formerly-rejected return inside if")
    compile_and_execute(cc, "invalid_return_in_while", 0,
                        "formerly-rejected return inside while")

    # 0.18.0: explicit external declarations + expression statements.
    puts_text = compile_assembly(cc, "puts_string", "extern puts expression statement")
    req(".extern puts" in puts_text, "explicit extern emits unresolved puts symbol")
    req("call puts" in puts_text, "expression statement emits puts call")
    req("expression statement (result discarded)" in puts_text,
        "bare function call is represented as expression statement")
    req("movi r0, .Lstr_" in puts_text, "string address loaded as call argument")
    req(".section .data" in puts_text, "string literal emitted in data section")
    req(".byte 72, 105, 0" in puts_text, "string bytes are zero terminated")

    bad_ext = run([str(cc), "-S", str(CASES / "invalid_external_arity.c"),
                   "-o", str(BUILD / "invalid_external_arity.s")])
    req(bad_ext.returncode != 0, "reject wrong external function arity")
    req("function argument count mismatch" in bad_ext.stderr,
        "external arity diagnostic", bad_ext.stdout + bad_ext.stderr)

    bad_expr_call = run([str(cc), "-S",
                         str(CASES / "invalid_expression_call_undeclared.c"),
                         "-o", str(BUILD / "invalid_expression_call_undeclared.s")])
    req(bad_expr_call.returncode != 0,
        "reject undeclared function in expression statement")
    req("call to undefined function" in bad_expr_call.stderr,
        "undeclared expression-call diagnostic",
        bad_expr_call.stdout + bad_expr_call.stderr)

    # 0.19.0: first int-pointer / lvalue-rvalue groundwork.
    pointer_text = compile_assembly(cc, "pointer_address_deref",
                                    "address-of and dereference")
    req("mov  r1, r15" in pointer_text or "add  r1, r15, r10" in pointer_text,
        "address-of materializes local object address")
    req("ldw  r0, [r0]" in pointer_text,
        "dereference loads through pointer value")
    compile_and_execute(cc, "pointer_address_deref", 42,
                        "address-of/dereference")

    pointer_store = compile_assembly(cc, "pointer_store",
                                     "store through pointer")
    req("store through int pointer p" in pointer_store,
        "indirect assignment is represented explicitly")
    req("stw  r1, [r2]" in pointer_store,
        "indirect assignment emits STW through pointer")
    compile_and_execute(cc, "pointer_store", 73,
                        "store through pointer")
    compile_and_execute(cc, "pointer_store_return_deref", 73,
                        "pointer assignment/store/dereference")

    bad_deref = run([str(cc), "-S", str(CASES / "invalid_deref_int.c"),
                     "-o", str(BUILD / "invalid_deref_int.s")])
    req(bad_deref.returncode != 0, "reject dereference of non-pointer int")
    req("dereference requires a pointer local" in bad_deref.stderr,
        "non-pointer dereference diagnostic", bad_deref.stderr)

    bad_store = run([str(cc), "-S",
                     str(CASES / "invalid_indirect_store_int.c"),
                     "-o", str(BUILD / "invalid_indirect_store_int.s")])
    req(bad_store.returncode != 0, "reject indirect store through non-pointer int")
    req("indirect assignment requires a pointer local" in bad_store.stderr,
        "non-pointer indirect-store diagnostic", bad_store.stderr)

    # 0.20.0: char scalars, char pointers, and byte-width memory access.
    char_scalar = compile_assembly(cc, "char_scalar", "char scalar truncation")
    req("stb  r1, [r15]" in char_scalar,
        "char scalar initializer stores one byte")
    req("ldb  r0, [r15]" in char_scalar,
        "char scalar expression loads one byte")
    req("0x000000FF" in char_scalar,
        "char scalar assignment truncates to eight bits")
    compile_and_execute(cc, "char_scalar", 44,
                        "char scalar truncation")

    char_load = compile_assembly(cc, "char_pointer_load", "char pointer load")
    req("ldb  r0, [r0]" in char_load,
        "char pointer dereference emits LDB")
    compile_and_execute(cc, "char_pointer_load", 65,
                        "char pointer dereference")

    char_store = compile_assembly(cc, "char_pointer_store", "char pointer store")
    req("store through char pointer p" in char_store,
        "char indirect assignment preserves pointee type")
    req("stb  r1, [r2]" in char_store,
        "char pointer indirect assignment emits STB")
    compile_and_execute(cc, "char_pointer_store", 66,
                        "char pointer store")

    typed_puts = compile_assembly(cc, "char_pointer_typed_puts",
                                  "typed char-pointer puts")
    req(".extern puts" in typed_puts,
        "typed puts remains an ordinary unresolved external")
    req("initialize local char * message" in typed_puts,
        "string literal initializes char pointer local")
    req("call puts" in typed_puts,
        "char pointer is passed through normal call ABI")
    compile_and_execute(cc, "char_pointer_typed_puts", 7,
                        "typed char-pointer puts")

    # 0.21.0: typed pointer arithmetic.
    char_add = compile_assembly(cc, "pointer_arith_char_add",
                                "char pointer addition")
    req("movi r2, 0x00000001" in char_add and
        "add  r1, r1, r2" in char_add,
        "char pointer addition advances by one byte")
    req("mul  r2, r2" not in char_add,
        "char pointer addition requires no scaling multiply")
    compile_and_execute(cc, "pointer_arith_char_add", 66,
                        "char pointer addition")

    char_sub = compile_assembly(cc, "pointer_arith_char_sub",
                                "char pointer subtraction")
    req("sub  r1, r1, r2" in char_sub,
        "char pointer subtraction advances backward by one byte")
    compile_and_execute(cc, "pointer_arith_char_sub", 65,
                        "char pointer subtraction")

    int_add = compile_assembly(cc, "pointer_arith_int_add",
                               "int pointer addition")
    req("movi r10, 0x00000004" in int_add and
        "mul  r2, r2, r10" in int_add,
        "int pointer addition scales index by four")
    req("add  r1, r1, r2" in int_add,
        "scaled int pointer offset is added to address")
    compile_and_execute(cc, "pointer_arith_int_add", 22,
                        "int pointer addition")

    int_sub = compile_assembly(cc, "pointer_arith_int_sub",
                               "int pointer subtraction")
    req("mul  r2, r2, r10" in int_sub and
        "sub  r1, r1, r2" in int_sub,
        "int pointer subtraction scales index by four")
    compile_and_execute(cc, "pointer_arith_int_sub", 11,
                        "int pointer subtraction")

    bad_ptr_ptr = run([str(cc), "-S",
                       str(CASES / "invalid_pointer_pointer_add.c"),
                       "-o", str(BUILD / "invalid_pointer_pointer_add.s")])
    req(bad_ptr_ptr.returncode != 0,
        "reject pointer plus pointer")
    req("does not yet support pointer-to-pointer arithmetic" in bad_ptr_ptr.stderr,
        "pointer-plus-pointer diagnostic", bad_ptr_ptr.stderr)

    bad_int_ptr = run([str(cc), "-S",
                       str(CASES / "invalid_integer_pointer_add.c"),
                       "-o", str(BUILD / "invalid_integer_pointer_add.s")])
    req(bad_int_ptr.returncode != 0,
        "reject integer plus pointer in Stage 21")
    req("requires the pointer on the left" in bad_int_ptr.stderr,
        "integer-plus-pointer diagnostic", bad_int_ptr.stderr)

    # 0.22.0: fixed-size local arrays and subscripting.
    int_array = compile_assembly(cc, "array_int_basic", "int array subscripting")
    req("store int array element a[index]" in int_array,
        "int array assignment emits indexed store")
    req("mul  r2, r2, r10" in int_array,
        "int array index scales by four")
    req("ldw  r0, [r0]" in int_array,
        "int array subscript emits LDW")
    compile_and_execute(cc, "array_int_basic", 30, "int array subscripting")

    char_array = compile_assembly(cc, "array_char_basic", "char array subscripting")
    req("store char array element s[index]" in char_array,
        "char array assignment emits indexed store")
    req("stb  r1, [r3]" in char_array and "ldb  r0, [r0]" in char_array,
        "char array uses byte loads and stores")
    compile_and_execute(cc, "array_char_basic", 66, "char array subscripting")

    compile_and_execute(cc, "array_index_variable", 77, "variable array index")
    compile_and_execute(cc, "array_decay_int_pointer", 22, "int array decay to pointer")
    compile_and_execute(cc, "array_decay_char_pointer", 66, "char array decay to pointer")

    bad_zero_array = run([str(cc), "-S", str(CASES / "invalid_array_zero.c"),
                          "-o", str(BUILD / "invalid_array_zero.s")])
    req(bad_zero_array.returncode != 0, "reject zero-length array")
    req("array length must be a positive integer constant" in bad_zero_array.stderr,
        "zero-length array diagnostic", bad_zero_array.stderr)

    bad_array_init = run([str(cc), "-S", str(CASES / "invalid_array_initializer.c"),
                          "-o", str(BUILD / "invalid_array_initializer.s")])
    req(bad_array_init.returncode != 0, "reject Stage 22 array initializer")
    req("does not support array initializers" in bad_array_init.stderr,
        "array initializer diagnostic", bad_array_init.stderr)

    # 0.23.0: named structs and local member access.
    struct_basic = compile_assembly(cc, "struct_basic", "basic struct members")
    req("8-byte stack frame" in struct_basic,
        "two-int struct reserves eight-byte object")
    req("store struct member p + 0" in struct_basic and
        "store struct member p + 4" in struct_basic,
        "struct members use fixed compile-time offsets")
    req("ldw  r0, [r15]" in struct_basic,
        "first int member loads as word")
    compile_and_execute(cc, "struct_basic", 42,
                        "basic struct members")

    struct_char = compile_assembly(cc, "struct_char_member",
                                   "char/int struct layout")
    req("stb  r1, [r15]" in struct_char,
        "char struct member stores as byte")
    req("ldb  r0, [r15]" in struct_char,
        "char struct member loads as byte")
    req("0x00000004" in struct_char,
        "int member following char is aligned to offset four")
    compile_and_execute(cc, "struct_char_member", 86,
                        "char/int struct layout")

    two_structs = compile_assembly(cc, "struct_two_objects",
                                   "multiple struct locals")
    req("16-byte stack frame" in two_structs,
        "two eight-byte structs reserve sixteen bytes")
    req("0x00000008" in two_structs and "0x0000000C" in two_structs,
        "second struct object receives independent member addresses")
    compile_and_execute(cc, "struct_two_objects", 55,
                        "multiple struct locals")

    bad_member = run([str(cc), "-S",
                      str(CASES / "invalid_struct_unknown_member.c"),
                      "-o", str(BUILD / "invalid_struct_unknown_member.s")])
    req(bad_member.returncode != 0,
        "reject unknown struct member")
    req("unknown struct member" in bad_member.stderr,
        "unknown struct member diagnostic", bad_member.stderr)

    bad_struct_type = run([str(cc), "-S",
                           str(CASES / "invalid_struct_unknown_type.c"),
                           "-o", str(BUILD / "invalid_struct_unknown_type.s")])
    req(bad_struct_type.returncode != 0,
        "reject unknown struct type")
    req("unknown struct type" in bad_struct_type.stderr,
        "unknown struct type diagnostic", bad_struct_type.stderr)

    bad_struct_pointer = run([str(cc), "-S",
                              str(CASES / "invalid_struct_pointer.c"),
                              "-o", str(BUILD / "invalid_struct_pointer.s")])
    req(bad_struct_pointer.returncode != 0,
        "reject Stage 23 struct pointer")
    req("struct pointers are not yet supported" in bad_struct_pointer.stderr,
        "struct pointer boundary diagnostic", bad_struct_pointer.stderr)

    # 0.24.0: struct pointers and the -> operator.
    struct_ptr = compile_assembly(cc, "struct_pointer_arrow",
                                  "struct pointer arrow")
    req("store struct member q + 0" in struct_ptr and
        "store struct member q + 4" in struct_ptr,
        "arrow stores use struct member offsets")
    req("ldw  r0, [r0]" in struct_ptr or "ldw  r1, [r1]" in struct_ptr,
        "arrow member reads dereference pointer-derived address")
    compile_and_execute(cc, "struct_pointer_arrow", 42,
                        "struct pointer arrow")

    struct_ptr_char = compile_assembly(cc, "struct_pointer_char",
                                       "struct pointer char member")
    req("stb  r1, [r10]" in struct_ptr_char,
        "arrow char member stores as byte")
    req("ldb" in struct_ptr_char,
        "arrow char member loads as byte")
    compile_and_execute(cc, "struct_pointer_char", 86,
                        "struct pointer char member")

    compile_and_execute(cc, "struct_pointer_reassign", 42,
                        "struct pointer reassignment")

    bad_arrow = run([str(cc), "-S",
                     str(CASES / "invalid_arrow_nonpointer.c"),
                     "-o", str(BUILD / "invalid_arrow_nonpointer.s")])
    req(bad_arrow.returncode != 0,
        "reject arrow on non-pointer struct object")
    req("arrow requires a struct pointer local" in bad_arrow.stderr,
        "non-pointer arrow diagnostic", bad_arrow.stderr)

    bad_dot_ptr = run([str(cc), "-S",
                       str(CASES / "invalid_dot_struct_pointer.c"),
                       "-o", str(BUILD / "invalid_dot_struct_pointer.s")])
    req(bad_dot_ptr.returncode != 0,
        "reject dot on struct pointer")
    req("dot member access requires a struct object" in bad_dot_ptr.stderr,
        "struct-pointer dot diagnostic", bad_dot_ptr.stderr)

    # Verbose mode remains opt-in.
    verbose_obj = BUILD / "verbose.o"
    verbose = run([str(cc), "-v", "-c", str(CASES / "local_add_constant.c"), "-o", str(verbose_obj)])
    req(verbose.returncode == 0 and "invoke: t32-as" in verbose.stdout, "-v shows invoked phase", verbose.stdout + verbose.stderr)

    # Semantic and syntax negatives.
    negatives = [
        ("assignment_undeclared.c", "assignment to undeclared local variable", "undeclared assignment"),
        ("expression_undeclared_rhs.c", "use of undeclared local variable", "undeclared expression operand"),
        ("invalid_bare_bang.c", "invalid token", "unsupported unary bang"),
        ("invalid_triple_equal.c", "expected integer literal or local variable", "malformed triple equality"),
        ("invalid_missing_rparen.c", "expected ')'", "missing closing parenthesis"),
        ("invalid_empty_parentheses.c", "expected integer literal or local variable", "empty parentheses"),
        ("invalid_else_without_if.c", "use of undeclared local variable", "else without if"),
        ("invalid_while_missing_rparen.c", "expected ')'", "while missing closing parenthesis"),
        ("undeclared_local.c", "undeclared local variable", "undeclared local"),
        ("invalid_function.c", "translation unit requires main", "translation unit without main"),
        ("invalid_missing_semicolon.c", "expected ';'", "missing semicolon"),
        ("multi_duplicate_local.c", "duplicate local variable", "duplicate local"),
        ("multi_late_declaration.c", "local declarations before executable statements", "late local declaration"),
        ("init_self_reference.c", "use of undeclared local variable", "self-referencing initializer"),
        ("init_forward_reference.c", "use of undeclared local variable", "forward-referencing initializer"),
        ("invalid_break_outside.c", "break statement is not inside a loop", "break outside loop"),
        ("invalid_continue_outside.c", "continue statement is not inside a loop", "continue outside loop"),
        ("invalid_for_missing_semicolon.c", "expected ';'", "for missing semicolon"),
        ("function_bad_arity.c", "function argument count mismatch", "wrong function arity"),
        ("function_undefined.c", "call to undefined function", "undefined function call"),
    ]

    for case_name, needle, label in negatives:
        destination = BUILD / f"negative_{case_name}.s"
        result = run([str(cc), "-S", str(CASES / case_name), "-o", str(destination)])
        req(result.returncode != 0, f"reject {label}")
        req(needle in result.stderr, f"{label} diagnostic", result.stderr)
        req(not destination.exists(), f"{label} leaves no output")

    mode_conflict = run([str(cc), "-S", "-c", str(CASES / "return_0.c")])
    req(mode_conflict.returncode != 0, "reject -S with -c")
    req("cannot be used together" in mode_conflict.stderr, "mode conflict diagnostic", mode_conflict.stderr)

    missing_binary = BUILD / "missing.bin"
    environment = os.environ.copy()
    environment["T32_PREFIX"] = str(BUILD / "no-runtime")
    missing_runtime = run(
        [str(cc), str(CASES / "return_0.c"), "-o", str(missing_binary)],
        env=environment,
    )
    req(missing_runtime.returncode != 0, "missing runtime rejected")
    req("missing startup object" in missing_runtime.stderr, "missing runtime diagnostic", missing_runtime.stderr)
    req(not missing_binary.exists(), "failed link leaves no binary")

    absent = run([str(cc), "-S", str(CASES / "does-not-exist.c")])
    req(absent.returncode != 0, "missing source rejected")
    req("cannot open" in absent.stderr, "missing source diagnostic", absent.stderr)

    print(f"t32-cc: PASS ({PASS_COUNT}/{PASS_COUNT} cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
