; generated by t32-cc 0.16.0
; Stage 17 ABI 0.1 translation unit

.section .text
.global main

main:
    ; 1 local int(s), 4-byte stack frame
    subi r15, r15, 4
    ; initialize local int x at [r15 + 0]
    movi r1, 0x0000002A
    stw  r1, [r15]
    ; assign x
    ldw  r1, [r15]
    movi r2, 0x00000006
    div  r1, r1, r2
    stw  r1, [r15]
    ldw  r0, [r15]
.Lreturn_main:
    addi r15, r15, 4
    ret
