; generated by t32-cc 0.16.0
; Stage 17 ABI 0.1 translation unit

.section .text
.global main

main:
    movi r0, 0xFFFFFFFB
    movi r1, 0x00000003
    sub  r10, r0, r1
    xor  r11, r0, r1
    and  r12, r11, r0
    not  r11, r11
    and  r11, r11, r10
    or   r10, r12, r11
    movi r11, 0x0000001F
    shr  r0, r10, r11
.Lreturn_main:
    ret
