; generated by t32-cc 0.16.0
; Stage 17 ABI 0.1 translation unit

.section .text
.global main

main:
    movi r0, 0x0000000E
    movi r1, 0x0000000D
    xor  r0, r0, r1
    movi r10, 0x00000000
    sub  r10, r10, r0
    or   r0, r0, r10
    movi r10, 0x0000001F
    shr  r0, r0, r10
.Lreturn_main:
    ret
