; generated by t32-cc 0.4.0
; Stage 5 ABI 0.1 translation unit

.section .text
.global main

main:
    ; local int x occupies 4 bytes at [r15]
    subi r15, r15, 4
    movi r1, 0x00000005
    stw  r1, [r15]
    movi r0, 0x00000003
    ldw  r1, [r15]
    add  r0, r0, r1
    addi r15, r15, 4
    ret
