; generated by t32-cc 0.16.0
; Stage 17 ABI 0.1 translation unit

.section .text
.global main

main:
    ; 1 local int(s), 4-byte stack frame
    subi r15, r15, 4
    ; initialize local int x at [r15 + 0]
    movi r1, 0x00000006
    stw  r1, [r15]
    movi r0, 0x00000007
    ldw  r1, [r15]
    mul  r0, r0, r1
.Lreturn_main:
    addi r15, r15, 4
    ret
