; generated by t32-cc 0.16.0
; Stage 17 ABI 0.1 translation unit

.section .text
.global main

main:
    ; 1 local int(s), 4-byte stack frame
    subi r15, r15, 4
    ; initialize local int x at [r15 + 0]
    movi r1, 0x00000063
    stw  r1, [r15]
    ; for initializer
    movi r1, 0x00000000
    stw  r1, [r15]
.Lfor_0:
    ; for condition
    ldw  r0, [r15]
    movi r1, 0x00000005
    sub  r10, r0, r1
    xor  r11, r0, r1
    and  r12, r11, r0
    not  r11, r11
    and  r11, r11, r10
    or   r10, r12, r11
    movi r11, 0x0000001F
    shr  r0, r10, r11
    jz   r0, .Lendfor_0
.Lfor_update_0:
    ; for update
    ldw  r1, [r15]
    movi r2, 0x00000001
    add  r1, r1, r2
    stw  r1, [r15]
    jmp  .Lfor_0
.Lendfor_0:
    ldw  r0, [r15]
.Lreturn_main:
    addi r15, r15, 4
    ret
