; generated by t32-cc 0.16.0
; Stage 17 ABI 0.1 translation unit

.section .text
.global main

add:
    ; 2 parameter/local slot(s), 8-byte stack frame
    subi r15, r15, 8
    ; parameter int a from r0
    stw  r0, [r15]
    ; parameter int b from r1
    movi r10, 0x00000004
    add  r10, r15, r10
    stw  r1, [r10]
    ldw  r0, [r15]
    movi r10, 0x00000004
    add  r10, r15, r10
    ldw  r1, [r10]
    add  r0, r0, r1
.Lreturn_add:
    addi r15, r15, 8
    ret

main:
    ; 0 local int(s), 64-byte stack frame
    subi r15, r15, 64
    movi r0, 0x0000000A
    stw  r0, [r15]
    movi r0, 0x00000014
    movi r10, 0x00000004
    add  r10, r15, r10
    stw  r0, [r10]
    ldw  r0, [r15]
    movi r10, 0x00000004
    add  r10, r15, r10
    ldw  r1, [r10]
    call add
.Lreturn_main:
    addi r15, r15, 64
    ret
