; generated by t32-cc 0.16.0
; Stage 17 ABI 0.1 translation unit

.section .text
.global main

main:
    ; 1 local int(s), 4-byte stack frame
    subi r15, r15, 4
    ; initialize local int x at [r15 + 0]
    movi r1, 0x00000005
    stw  r1, [r15]
    ; if condition
    ldw  r0, [r15]
    movi r1, 0x0000000A
    sub  r10, r0, r1
    xor  r11, r0, r1
    and  r12, r11, r0
    not  r11, r11
    and  r11, r11, r10
    or   r10, r12, r11
    movi r11, 0x0000001F
    shr  r0, r10, r11
    jz   r0, .Lelse_0
    ; assign x
    movi r1, 0x00000014
    stw  r1, [r15]
    jmp  .Lendif_0
.Lelse_0:
    ; assign x
    movi r1, 0x0000001E
    stw  r1, [r15]
.Lendif_0:
    ldw  r0, [r15]
.Lreturn_main:
    addi r15, r15, 4
    ret
