; generated by t32-cc 0.16.0
; Stage 17 ABI 0.1 translation unit

.section .text
.global main

main:
    ; 2 local int(s), 8-byte stack frame
    subi r15, r15, 8
    ; initialize local int x at [r15 + 0]
    movi r1, 0x00000005
    stw  r1, [r15]
    ; initialize local int y at [r15 + 4]
    ldw  r1, [r15]
    movi r2, 0x00000003
    add  r1, r1, r2
    movi r10, 0x00000004
    add  r10, r15, r10
    stw  r1, [r10]
    movi r10, 0x00000004
    add  r10, r15, r10
    ldw  r0, [r10]
.Lreturn_main:
    addi r15, r15, 8
    ret
