; generated by t32-cc 0.4.0
; Stage 5 ABI 0.1 translation unit

.section .text
.global main

main:
    ; local int answer occupies 4 bytes at [r15]
    subi r15, r15, 4
    movi r1, 0xFFFFFFF9
    stw  r1, [r15]
    ldw  r0, [r15]
    addi r15, r15, 4
    ret
