; generated by t32-cc 0.16.0
; Stage 17 ABI 0.1 translation unit

.section .text
.global main

main:
    movi r0, 0x00000014
    movi r1, 0x00000006
    div  r13, r0, r1
    mul  r13, r13, r1
    sub  r0, r0, r13
.Lreturn_main:
    ret
